"""Provider protocols, registries, and optional local/remote adapters."""

from trade_research.providers.contracts import (
    MAX_FILING_ROWS,
    MAX_FUNDAMENTAL_ROWS,
    MAX_HTTP_BYTES,
    MAX_LOCAL_BYTES,
    MAX_OUTCOME_POINTS,
    MAX_PRICE_POINTS,
    FilingProvider,
    FundamentalProvider,
    FundamentalStatementMetadata,
    FundamentalValuationMetadata,
    OptionalProviderDependencyError,
    OutcomePoint,
    OutcomeSeries,
    OutcomeSeriesProvider,
    PortfolioProvider,
    PricePoint,
    PriceProvider,
    ProviderConfigurationError,
    ProviderContractError,
)
from trade_research.providers.inline import InlineOutcomeProvider, InlinePriceProvider
from trade_research.providers.local import (
    LocalCsvParquetFundamentalProvider,
    LocalCsvParquetPriceProvider,
    LocalPortfolioProvider,
    ReadOnlySqlFundamentalProvider,
    ReadOnlySqlPriceProvider,
)
from trade_research.providers.registry import CapabilityName, ProviderRegistry
from trade_research.providers.remote import (
    BloombergPriceProvider,
    CcxtPriceProvider,
    YahooPriceProvider,
    resolve_provider_symbol,
)
from trade_research.providers.sec import (
    CikResolver,
    SecCompanyFactsProvider,
    SecFilingsProvider,
)

__all__ = [
    "CcxtPriceProvider",
    "BloombergPriceProvider",
    "CikResolver",
    "CapabilityName",
    "FilingProvider",
    "FundamentalProvider",
    "FundamentalStatementMetadata",
    "FundamentalValuationMetadata",
    "LocalCsvParquetFundamentalProvider",
    "LocalCsvParquetPriceProvider",
    "LocalPortfolioProvider",
    "InlinePriceProvider",
    "InlineOutcomeProvider",
    "MAX_FILING_ROWS",
    "MAX_FUNDAMENTAL_ROWS",
    "MAX_HTTP_BYTES",
    "MAX_LOCAL_BYTES",
    "MAX_OUTCOME_POINTS",
    "MAX_PRICE_POINTS",
    "OptionalProviderDependencyError",
    "OutcomePoint",
    "OutcomeSeries",
    "OutcomeSeriesProvider",
    "PortfolioProvider",
    "PricePoint",
    "PriceProvider",
    "ProviderConfigurationError",
    "ProviderContractError",
    "ProviderRegistry",
    "ReadOnlySqlFundamentalProvider",
    "ReadOnlySqlPriceProvider",
    "SecCompanyFactsProvider",
    "SecFilingsProvider",
    "YahooPriceProvider",
    "resolve_provider_symbol",
]
